#! /usr/bin/env python
from config_index import *
import rospy
import rosbag
from geometry_msgs.msg import Twist
from std_msgs.msg import Int32, String
import genpy
from rqt_TheTeleop.msg import boton_data


ls=["/odom",Twist(),genpy.Time(1,0),Twist]
store_dict=dict([("1",ls)])
store(store_dict, "test")

store_dict2=restore()